#!/bin/sh
rm -f /usr/lib/luna/java/GstService.jar
rm -f /usr/share/dbus-1/system-services/ca.canucksoftware.videocam.service
rm -f /etc/event.d/videocam
mv -f /usr/bin/gst-launch.BACKUP /usr/bin/gst-launch
mv -f /usr/bin/gst-launch-0.10.BACKUP /usr/bin/gst-launch-0.10

if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop java-serviceboot
    /sbin/start java-serviceboot
fi

exit 0
