#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.gstservice.jar
ln -s /var/usr/lib/luna/java/org.webosinternals.gstservice.jar /usr/lib/luna/java/org.webosinternals.gstservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.gstservice.service
ln -s /var/usr/share/dbus-1/system-services/org.webosinternals.gstservice.service /usr/share/dbus-1/system-services/org.webosinternals.gstservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.gstservice
cp /var/etc/event.d/org.webosinternals.gstservice /etc/event.d/org.webosinternals.gstservice

# Restart the service handler (this also starts this service)
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop java-serviceboot
    /sbin/start java-serviceboot
fi

# These should be done by the library
# mv -f /usr/bin/gst-launch /usr/bin/gst-launch.BACKUP
# mv -f /usr/bin/gst-launch-0.10 /usr/bin/gst-launch-0.10.BACKUP
# mv -f /var/usr/bin/gst-launch /usr/bin/gst-launch
# mv -f /var/usr/bin/gst-launch-0.10 /usr/bin/gst-launch-0.10

exit 0
