#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.gstservice.jar
cp $IPKG_OFFLINE_ROOT/usr/lib/luna/java/org.webosinternals.gstservice.jar /usr/lib/luna/java/org.webosinternals.gstservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.gstservice.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/org.webosinternals.gstservice.service /usr/share/dbus-1/system-services/org.webosinternals.gstservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.gstservice
cp $IPKG_OFFLINE_ROOT/etc/event.d/org.webosinternals.gstservice /etc/event.d/org.webosinternals.gstservice

exit 0
