#!/bin/sh

# Stop the service
/sbin/stop org.webosinternals.gstservice

# Remove the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.gstservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.gstservice.service

# Remove the upstart script
rm -f /etc/event.d/org.webosinternals.gstservice

# Restart the service handler
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop java-serviceboot
    /sbin/start java-serviceboot
fi

exit 0
